### ISSUE TITLE
free_fleet_client_ros2 build fails for Foxy

### ISSUE THREAD

**Issue by sachin-rr** [open-rmf/free_fleet#110]
### Required information:

- Operating system and version:
  - Ubuntu 20.04 
- ROS distribution and version:
  - Foxy 
- ROS installation type:
  - Binary 
- Package or library, if applicable:
  - Free Fleet 

### Description of the bug

Not able to compile the Free Fleet Client ROS2 pkg

### Steps to reproduce the bug

1. clone the free_fleet repo in the colcon_ws/src
2. build using colcon build

**std err log file** 

[stderr.log](https://github.com/open-rmf/free_fleet/files/7635356/stderr.log)

### Expected behavior

Build Success

### Actual behavior

Build Failed

**Comment by aaronchongth** [comment]
Hello @sachin-rr! Thank you for reporting this, we have just recently added support for the ROS 2 client https://github.com/open-rmf/free_fleet/pull/106, however that is currently only targeting `Galactic`.

If you would like to use just the server in Foxy, you could skip the compilation of `free_fleet_client_ros2` using
```
colcon build --packages-skip free_fleet_client_ros2
```

**Comment by sachin-rr** [comment]
Thanks for your response.
Will there be support for `free_fleet_client_ros2` pkg on Foxy, since Galactic is not LTS?
If possible, I can contribute to support `free_fleet_client_ros2` pkg for Foxy.

**Comment by eliasdc** [comment]
I'll check if I can support both Galactic and Foxy with the same branch. Shouldn't be that much effort.

**Comment by eliasdc** [comment]
@sachin-rr Could you test the branch for the pull request? I'm not able to run my setup entirely but it does compile.

**Comment by sachin-rr** [comment]
@eliasdc  @aaronchongth Thank you so much :heart: 
Tested the pull request. 
Compilation is successful and able to send the goal from the free fleet server to nav2 for tb3.
Closing the issue.

**Comment by sachin-rr** [comment]
Are we merge pull request #112  to main branch?

**Comment by eliasdc** [comment]
When it has been reviewed and remarks have been solved it will be merged into main branch.
