### ISSUE TITLE
Nav2 robot sometimes do not move immediately when sending task from RMF.

### ISSUE THREAD

**Issue by shifsa** [open-rmf/free_fleet#119]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  -  From source
- OpenRMF version or commit hash
  - latest
- ROS distribution and version:
  - ROS2 Galactic
- ROS installation type:
  - from Docker
- Package or library, if applicable:
  - FreeFleet,Navigation2,turtlebot3

### Description of the bug

Sometimes robot does not move immediately when a task is sent from the RMF.

### Steps to reproduce the bug
1. I am using FreeFleet to connect RMF with Turtlebot3 running on Navigation2 on Gazebo.
2. I send Loop task from RMF Panel to its Turtlebot3.

### Expected behavior

Turtlebot3 on Gazebo is moving quickly.

### Actual behavior

After a short time, the robot begins to move.

### Additional information

Looking at /fleet_states topic, there is an instruction set to wait in place for 30 seconds (Responsive Wait?) when I have not sent a task from RMF.
I am assuming that the robot is stuck until it completes.

**Comment by aaronchongth** [comment]
Hello @shifsa! Could you elaborate a little more on the issue, perhaps how long did it take for the robot to start moving in these scenarios? 

As for `Responsive Wait`, it is a mechanism in RMF that allows for re-routing these stationary robots (after it has completed its task and the finishing task is `nothing`), to allow other robots to pass through those lanes and waypoints. These `Responsive Wait` tasks, should be overwritten by new incoming tasks without the need to wait for it to be completed. In your scenario, is it the case that the robot waits for 30 seconds before it starts moving?

**Comment by shifsa** [comment]
Each time I submit a task, the time it takes for the robot to start moving varies.(max 30 seconds)
When I do not submit a task, the FreeFleet log shows the following.
`[free_fleet_client_ros2-2] [INFO] [1660801148.050725901] [turtlebot3_burger1.turtlebot3_free_fleet_client_node]: we reached our goal early! Waiting 29.33 more seconds`
As long as this log is displayed, the robot does not move even if I send a task.
Only the yellow ball of rmf_visualization starts moving.
<img src="https://user-images.githubusercontent.com/111342933/185305135-07bdf751-2eb9-40c5-a596-c79da7f3c185.png" width="200px">

After that, when the following log appears, the yellow ball reverts to a purple ball and the robot on Gazebo begins to move.
`[free_fleet_client_ros2-2] [INFO] [1660801179.552140857] [turtlebot3_burger1.turtlebot3_free_fleet_client_node]: we reached our goal early! Waiting 0.01 more seconds`

**Comment by shifsa** [comment]
Hello, @aaronchongth .
The video below recreates the situation.

https://user-images.githubusercontent.com/111342933/187632490-d081b51a-c317-48a1-90ec-2e995d4aa8a8.mp4

**Comment by aaronchongth** [comment]
Hello @shifsa! I am able to replicate what you were facing, and I believe I have found a fix, https://github.com/open-rmf/free_fleet/pull/120.

My preliminary tests look good at the moment. Let me know if you still face issues with this fix.

**Comment by shifsa** [comment]
Hello, @aaronchongth .
Thanks for fixing the code.
It now works properly here too!
