### ISSUE TITLE
error for turtlebot3_world_burger.yaml 

### ISSUE THREAD

**Issue by ncnynl** [open-rmf/free_fleet#123]
For humble  need to change from differential to nav2_amcl::DifferentialMotionModel

sed -i 's/differential/nav2_amcl::DifferentialMotionModel/'g ~/ros2_free_fleet_ws/src/free_fleet/ff_examples_ros2/params/turtlebot3_world_burger.yaml

**Comment by aaronchongth** [comment]
@ncnynl thanks for raising this! I tried it out and your solution indeed fixes it. Please confirm that it fixes it on your end too

**Comment by ncnynl** [comment]
@aaronchongth   Yes, i have fix it on my install script https://gitee.com/ncnynl/commands/blob/master/commands_extra/ros2_rmf/shell/install_rmf_free_fleet.sh

**Comment by ncnynl** [comment]
maybe  other all  turtlebot3_world_*.yaml files need to be changed
