### ISSUE TITLE
Issue with multiple turtlebot3 on Noetic ROS1

### ISSUE THREAD

**Issue by Kazimbalti** [open-rmf/free_fleet#133]
There is an issue with running multiple turtlebot3 on ROS1 Noetic.
Everything works well with single turtlebot3 but with multiple turtlebot3 gazeo shows multiple turtlebot3, but in rviz it shows only one with no navigation. I have attached the picture below,
 I think there are some issue with TF for multiple turtlebot3
![image](https://user-images.githubusercontent.com/32608321/224479365-c2056b1c-78d6-4e8d-a879-5c4360baee10.png)
, 
 Please someone help me how to resolve this issue?
 thank you

**Comment by siddux** [comment]
Hi @Kazimbalti,

just created a PR #134 solving the issue.

**Comment by aaronchongth** [comment]
Closing via https://github.com/open-rmf/free_fleet/pull/134
