### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by PVijayaGanesh** [open-rmf/free_fleet#147]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Ubuntu 22
ROS Distro : Humble
package : free_fleet

Issue :

aimavericks@aimavericks:~/ros2_free_fleet_ws$ colcon build
[0.298s] colcon.colcon_core.package_selection WARNING Some selected packages are already built in one or more underlay workspaces:
'free_fleet' is in: /home/aimavericks/ros2_rmf_ws/install/free_fleet
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
--allow-overriding free_fleet

This may be promoted to an error in a future release of colcon-override-check.
Starting >>> free_fleet
--- stderr: free_fleet
In file included from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:32,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.cpp:18:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_ModeRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:52:56: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
In file included from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.hpp:32,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.cpp:18:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_RobotState, 10>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.hpp:47:59: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
In file included from /usr/include/c++/12/bits/unique_ptr.h:36,
from /usr/include/c++/12/memory:75,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/include/free_fleet/Client.hpp:21,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:25:
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_ModeRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
In file included from /usr/include/c++/12/bits/unique_ptr.h:36,
from /usr/include/c++/12/memory:75,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/include/free_fleet/Server.hpp:21,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.hpp:25:
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_RobotState>, 10>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
In file included from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.hpp:32,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/Server.cpp:22:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_RobotState, 10>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ServerImpl.hpp:47:59: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
In file included from /usr/include/c++/12/bits/unique_ptr.h:36,
from /usr/include/c++/12/memory:75,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/include/free_fleet/Server.hpp:21,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/Server.cpp:20:
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_RobotState>, 10>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
In file included from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:32,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/Client.cpp:22:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_ModeRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:52:56: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
In file included from /usr/include/c++/12/bits/unique_ptr.h:36,
from /usr/include/c++/12/memory:75,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/include/free_fleet/Client.hpp:21,
from /home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/Client.cpp:20:
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_ModeRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_PathRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:56:56: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_PathRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_PathRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:56:56: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_PathRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_DestinationRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:60:63: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_DestinationRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp: In instantiation of ‘class free_fleet::dds::DDSSubscribeHandler<FreeFleetData_DestinationRequest>’:
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/ClientImpl.hpp:60:63: required from here
/home/aimavericks/ros2_free_fleet_ws/src/free_fleet/free_fleet/src/dds_utils/DDSSubscribeHandler.hpp:46:55: error: ‘free_fleet::dds::DDSSubscribeHandler<Message, MaxSamplesNum>::shared_msgs’ has incomplete type
46 | std::array<std::shared_ptr, MaxSamplesNum> shared_msgs;
| ^~~~~~~~~~~
/usr/include/c++/12/tuple:1595:45: note: declaration of ‘struct std::array<std::shared_ptr<FreeFleetData_DestinationRequest>, 1>’
1595 | template<typename _Tp, size_t _Nm> struct array;
| ^~~~~
**gmake[2]: *** [CMakeFiles/free_fleet.dir/build.make:76: CMakeFiles/free_fleet.dir/src/Client.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/free_fleet.dir/build.make:118: CMakeFiles/free_fleet.dir/src/Server.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/free_fleet.dir/build.make:90: CMakeFiles/free_fleet.dir/src/ClientImpl.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/free_fleet.dir/build.make:132: CMakeFiles/free_fleet.dir/src/ServerImpl.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/free_fleet.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Failed <<< free_fleet [0.46s, exited with code 2]**

Summary: 0 packages finished [0.74s]
1 package failed: free_fleet
1 package had stderr output: free_fleet
6 packages not processed

What might be the solution. I didn't the solution in any where. @arjo129 
please help me with this/....

**Comment by aaronchongth** [comment]
Hi @PVijayaGanesh! Thanks for reporting this, I've managed to reproduce the build error, will look into it soon. As @tomkimsour mentioned, it makes it rather difficult to read logs if it's pasted in this manner, in the future, either use a code block

```
like so
```

or use a link to a https://gist.github.com/

**Comment by PVijayaGanesh** [comment]
Hi Actually i solved like i build other humble installed linux system and transfer to the files my system and i solved..
Actually i want to run the openrmf on my turtlebot3 can you help me with i did upto free_fleet on my turtlebot3 bringing upthe bots using namespaces and please help me how to continue to rmf for that @aaronchongth @tomkimsour

**Comment by aaronchongth** [comment]
@PVijayaGanesh I've already pushed the single-line update via https://github.com/open-rmf/free_fleet/pull/150

Assuming you've already set up your map with `traffic-editor`, for example https://github.com/open-rmf/rmf_demos/tree/main/rmf_demos_maps, you'll need to launch all the nodes that make up the core of Open-RMF, for example https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos/launch/common.launch.xml. Then you'll need to spin up a `full_control` fleet adapter, something like https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/adapters/tinyRobot_adapter.launch.xml. You can reference some older tickets like https://github.com/open-rmf/free_fleet/issues/135, for more information.

For some more background information, the `full_control` fleet adapter is a legacy fleet adapter that does not support all the newer features of Open-RMF, and the `free_fleet` integration with it has been stale of a while now, we can't guarantee that everything will work perfectly as before.

We are currently working on https://github.com/open-rmf/free_fleet/pull/145, which is a newer iteration that supports the latest releases of Open-RMF, and moving away from DDS as the middleware between robot and server.

I'll be closing this ticket as the build issue has been fixed.

**Comment by PVijayaGanesh** [comment]
Thank you @aaronchongth . It helps me a lot

**Comment by PVijayaGanesh** [comment]
Hi @aaronchongth 
ros distro : galactic

command 1: ros2 launch ff_examples_ros2 turtlebot3_world_ff.launch.xml
command 2: ros2 launch ff_examples_ros2 turtlebot3_world_ff_server.launch.xml
command 3: ros2 launch rmf_pkg test.launch.xml which will launch the common.launch.xml and fleet_adapter..

rviz is opened wih the map and paths  but robots are not comming...
when launching 3rd command i am getting this issue..

[full_control-13] [ERROR] [1729060041.004614301] [turtlebot3_fleet_adapter]: Unable to compute a StartSet for robot [ros2_tb3_0] using level_name [] and location [0.000000, 0.000000, -1.894938] specified in its RobotState message. This can happen if the level_name in the RobotState message does not match any of the map names in the navigation graph supplied or if the location reported in the RobotState message is far way from the navigation graph. This robot will not be added to the fleet [turtlebot3]. The following hint may help with debugging: None of the waypoints in the graph are on a map called [].


please help me @aaronchongth @tomkimsour
