### ISSUE TITLE
[ERROR] [full_control-13]: process has died [pid 224157, exit code -6, cmd '/home/qdn/Work/open-rmf/free_fleet/ros2/install/rmf_fleet_adapter/lib/rmf_fleet_adapter/full_control --ros-args -r __node:=turtlebot3_fleet_adapter 

### ISSUE THREAD

**Issue by PVijayaGanesh** [open-rmf/free_fleet#152]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Command 1: roslaunch ff_examples_ros1 multi_turtlebot3_ff.launch
Command 2: ros2 launch ff_examples_ros2 turtlebot3_world_ff_server.launch.xml
Command 3: ros2 run ros1_bridge dynamic_bridge 
                     ```
logs for command3: check the list of supported pairs with the `--print-pairs` option
failed to create 2to1 bridge for topic '/map' with ROS 2 type 'rmf_building_map_msgs/msg/BuildingMap' and ROS 1 type 'nav_msgs/OccupancyGrid': No template specialization for the pair
check the list of supported pairs with the `--print-pairs` option
failed to create 1to2 bridge for topic '/map' with ROS 1 type 'nav_msgs/OccupancyGrid' and ROS 2 type 'rmf_building_map_msgs/msg/BuildingMap': No template specialization for the pair
```

Commad 4:  ros2 launch rmf_demos house.launch.xml

**Error**

` [INFO] [1729230163.747985672] [turtlebot3_fleet_adapter]: Parameter [reversible] set to: 1
[full_control-13] terminate called after throwing an instance of 'YAML::BadFile'
[full_control-13]   what():  bad file
[schedule_visualizer-5] [INFO] [1729230163.778540327] [rmf_visualization_schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[schedule_visualizer-5] [INFO] [1729230163.848365288] [rmf_visualization_schedule_data_node]: rmf_visualization_schedule_data_node started...
[schedule_visualizer-5] [INFO] [1729230163.851191717] [rmf_visualization_schedule_data_node]: Websocket server started on port: 8006
[schedule_visualizer-5] [INFO] [1729230163.870492347] [rmf_visualization_schedule_data_node]: Mirror handling new sync of 1 queries from schedule node version [0]
**[ERROR] [full_control-13]: process has died [pid 231911, exit code -6, cmd '/home/qdn/Work/open-rmf/free_fleet/ros2/install/rmf_fleet_adapter/lib/rmf_fleet_adapter/full_control --ros-args -r __node:=turtlebot3_fleet_adapter --params-file /tmp/launch_params_hnp__qge --params-file /tmp/launch_params_a868situ --params-file /tmp/launch_params_e4h91ddx --params-file /tmp/launch_params_qtojxhrp --params-file /tmp/launch_params_8k2trbpq --params-file /tmp/launch_params_tgs4x8aa --params-file /tmp/launch_params_soj0tgm6 --params-file /tmp/launch_params_9pynqhmt --params-file /tmp/launch_params_w81lk1fu --params-file /tmp/launch_params_3nek0_4z --params-file /tmp/launch_params_wjsmq6oq --params-file /tmp/launch_params_6orkactr --params-file /tmp/launch_params_cry0y273 --params-file /tmp/launch_params_2d1s91rp --params-file /tmp/launch_params_vvhbnybe --params-file /tmp/launch_params_jg9fnmh0 --params-file /tmp/launch_params_zdz356qk --params-file /tmp/launch_params_rfvncza7 --params-file /tmp/launch_params_aqjuoyq3 --params-file /tmp/launch_params_0pxd1jl9 --params-file /tmp/launch_params_9ixwxoew --params-file /tmp/launch_params__c70wklb --params-file /tmp/launch_params_dsy00u60 --params-file /tmp/launch_params_yi5v14jj --params-file /tmp/launch_params_p53olqnr --params-file /tmp/launch_params_edsjfzcs --params-file /tmp/launch_params_xflo_tja --params-file /tmp/launch_params_9p0kzyx5 --params-file /tmp/launch_params_lgwdrbmm --params-file /tmp/launch_params_13_ls73e'].**
[rmf_visualization_fleet_states-6] [INFO] [1729230164.006807691] [fleet_state_visualizer]: hello i am fleet state visualizer
[rviz2-8] [INFO] [1729230164.128753834] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-8] [INFO] [1729230164.129338560] [rviz2]: OpenGl version: 3.1 (GLSL 1.4)
[rmf_traffic_schedule_monitor-2] [INFO] [1729230164.210731350] [rmf_traffic_schedule_backup]: Liveliness changed event:
[rmf_traffic_schedule_monitor-2] [INFO] [1729230164.210791102] [rmf_traffic_schedule_backup]:   alive_count: 1
[rmf_traffic_schedule_monitor-2] [INFO] [1729230164.210875565] [rmf_traffic_schedule_backup]:   not_alive_count: 0
[rmf_traffic_schedule_monitor-2] [INFO] [1729230164.210913448] [rmf_traffic_schedule_backup]:   alive_count_change: 1
[rmf_traffic_schedule_monitor-2] [INFO] [1729230164.210930443] [rmf_traffic_schedule_backup]:   not_alive_count_change: 0
[rviz2-8] [INFO] [1729230164.242024529] [rviz2]: Stereo is NOT SUPPORTED
[building_map_server-4] [INFO] [1729230164.273782577] [building_map_server]: loading map path: /home/qdn/Work/open-rmf/free_fleet/ros2/install/rmf_demos_maps/share/rmf_demos_maps/house/house.building.yaml
[rmf_visualization_building_systems-7] [INFO] [1729230164.312131473] [building_systems_visualizer]: Building systems visualizer started...
[building_map_server-4] [INFO] [1729230164.349551916] [building_map_server]: opening: /home/qdn/Work/open-rmf/free_fleet/ros2/install/rmf_demos_maps/share/rmf_demos_maps/house/house.png
[building_map_server-4] [INFO] [1729230164.350526223] [building_map_server]: read 7056 byte image
[building_map_server-4] [INFO] [1729230164.353592532] [building_map_server]: publishing map...
[building_map_server-4] [INFO] [1729230164.354213601] [building_map_server]: ready to serve map: "house"  Ctrl+C to exit...
[schedule_visualizer-5] [INFO] [1729230164.409875507] [rmf_visualization_schedule_marker_publisher]: Rviz parameters updated
[schedule_visualizer-5] [INFO] [1729230165.270501746] [rmf_visualization_schedule_marker_publisher]: Received map "house" containing 1 level(s)
[schedule_visualizer-5] [INFO] [1729230165.270691315] [rmf_visualization_schedule_marker_publisher]: Level cache updated
[schedule_visualizer-5] [INFO] [1729230165.271061560] [rmf_visualization_schedule_marker_publisher]: Loading floorplan Image: house png
[rviz2-8] [INFO] [1729230165.291477755] [rviz2]: Trying to create a map of size 384 x 384 using 1 swatches
[rviz2-8] [ERROR] [1729230165.309476922] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-8] active samplers with a different type refer to the same texture image unit
[simple_api_server-12] [WARN] [1729230165.607113731] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230166.611612617] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230167.613804009] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230168.616869035] [api_client]: Dispatcher node is not avail, waiting...
[rmf_traffic_schedule_monitor-2] [INFO] [1729230168.650964673] [rmf_traffic_schedule_backup]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[schedule_visualizer-5] [INFO] [1729230168.774355779] [rmf_visualization_schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[simple_api_server-12] [WARN] [1729230169.629333268] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230170.633174957] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230171.636962540] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230172.640408601] [api_client]: Dispatcher node is not avail, waiting...
[simple_api_server-12] [WARN] [1729230173.643240436] [api_client]: Dispatcher node is not avail, waiting...
[rmf_traffic_schedule_monitor-2] [INFO] [1729230173.653715681] [rmf_traffic_schedule_backup]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
`

I am visualizing the rmf image like this..

file:///home/qdn/Pictures/errrmf

**Comment by akash-roboticist** [comment]
@PVijayaGanesh - can you confirm which version of ROS 2 are you using? If similar to https://github.com/open-rmf/free_fleet/issues/151, you are using `galactic`, things are unlikely to work.

**Comment by PVijayaGanesh** [comment]
Hi @akash-roboticist  Thank you for replying...

[full_control-13] [INFO] [1729235170.890769181] [turtlebot3_fleet_adapter]: Beginning new task [Chargebda92f] for [turtlebot3/tb3_1]. Remaining queue size: 1
[full_control-13] [INFO] [1729235170.898607506] [turtlebot3_fleet_adapter]: Robot [tb3_1] has begun waiting for its battery to charge to 100.0%. Please ensure that the robot is charging.


which parameter i need to change for assining task to the robot...
