### ISSUE TITLE
[Other issue]: Robot Position

### ISSUE THREAD

**Issue by harshp1509** [open-rmf/free_fleet#155]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

When i am integrating free fleet with open-rmf than i got robot in top-left corner not in map . so how can i get that robot onto map waypoints.
how to resolve this issue?

![Screenshot 2024-10-23 145708](https://github.com/user-attachments/assets/a344e02c-2300-46ab-8a72-d28692062ab3)

**Comment by aaronchongth** [comment]
Hey @harshp1509! Thanks for resolving the issue eventually. Could you perhaps write up a little on what the issue was and how you resolved it? This will help future users

**Comment by harshp1509** [comment]
@aaronchongth , changes the parameter from the free fleet server side.

  <param name="scale" value="0.928"/>
  <param name="rotation" value="-0.013"/>
  <param name="translation_x" value="-4.117"/>
  <param name="translation_y" value="27.26"/>

give the value based on your need.

**Comment by tomkimsour** [comment]
@harshp1509 how did you find these values ?
