### ISSUE TITLE
[Other issue]: Not an Issue need some help

### ISSUE THREAD

**Issue by pvg6** [open-rmf/free_fleet#158]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I integrated this openrmf into my robot they are working fine in my environment. I just want to perform some custom tasks. Like what changes need to make and where need to make..

I read this tutorial also :[]( https://osrf.github.io/ros2multirobotbook/task_userdefined.html)

Please help me...
I my setup for my robot i am using this adapter ----> **rmf_demos_fleet_adapter)/launch/fleet_adapter.launch.xml**

**Comment by Yadunund** [comment]
Please ask questions like this on our Discussions board after checking whether a similar questions has been asked previously. https://github.com/open-rmf/rmf/discussions
